"""Common SEC XBRL constants and base-metric concept mappings."""

COMMON_GAAP_CONCEPTS = {
    # Income statement
    "CostOfGoodsAndServicesSold",
    "CostOfRevenue",
    "CostsAndExpenses",
    "GeneralAndAdministrativeExpense",
    "GrossProfit",
    "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest",
    "IncomeTaxExpenseBenefit",
    "InterestExpenseNonOperating",
    "InterestIncomeExpenseNonOperatingNet",
    "NetIncomeLoss",
    "NetIncomeLossAvailableToCommonStockholdersBasic",
    "OperatingExpenses",
    "OperatingIncomeLoss",
    "ResearchAndDevelopmentExpense",
    "RevenueFromContractWithCustomerExcludingAssessedTax",
    "Revenues",
    "SalesRevenueNet",
    "SellingAndMarketingExpense",
    "SellingGeneralAndAdministrativeExpense",

    # Balance sheet
    "AccountsPayableCurrent",
    "AccountsReceivableNetCurrent",
    "AccruedLiabilitiesCurrent",
    "AccumulatedOtherComprehensiveIncomeLossNetOfTax",
    "Assets",
    "AssetsCurrent",
    "CashAndCashEquivalentsAtCarryingValue",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
    "CommonStocksIncludingAdditionalPaidInCapital",
    "ContractWithCustomerLiabilityCurrent",
    "ContractWithCustomerLiabilityNoncurrent",
    "DebtCurrent",
    "DebtNoncurrent",
    "DeferredRevenueCurrent",
    "DeferredRevenueNoncurrent",
    "DeferredTaxAssetsNet",
    "DeferredTaxLiabilitiesNoncurrent",
    "FinanceLeaseLiabilityCurrent",
    "FinanceLeaseLiabilityNoncurrent",
    "Goodwill",
    "IntangibleAssetsNetExcludingGoodwill",
    "InventoryNet",
    "Liabilities",
    "LiabilitiesAndStockholdersEquity",
    "LiabilitiesCurrent",
    "LongTermDebtAndFinanceLeaseObligationsCurrent",
    "LongTermDebtAndFinanceLeaseObligationsNoncurrent",
    "LongTermDebtCurrent",
    "LongTermDebtNoncurrent",
    "MarketableSecuritiesCurrent",
    "NoncontrollingInterestInConsolidatedEntity",
    "OperatingLeaseLiabilityCurrent",
    "OperatingLeaseLiabilityNoncurrent",
    "OperatingLeaseRightOfUseAsset",
    "OtherAssetsCurrent",
    "OtherAssetsNoncurrent",
    "OtherLiabilitiesCurrent",
    "OtherLiabilitiesNoncurrent",
    "PrepaidExpenseAndOtherAssetsCurrent",
    "PropertyPlantAndEquipmentNet",
    "RetainedEarningsAccumulatedDeficit",
    "ShortTermBorrowings",
    "ShortTermInvestments",
    "StockholdersEquity",
    "StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest",
    "TreasuryStockValue",

    # Cash flow statement
    "CashAndCashEquivalentsPeriodIncreaseDecrease",
    "CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect",
    "DepreciationDepletionAndAmortization",
    "DepreciationDepletionAndAmortizationExpense",
    "EffectOfExchangeRateOnCashAndCashEquivalents",
    "IncreaseDecreaseInAccountsPayable",
    "IncreaseDecreaseInAccountsReceivable",
    "IncreaseDecreaseInInventories",
    "NetCashProvidedByUsedInFinancingActivities",
    "NetCashProvidedByUsedInInvestingActivities",
    "NetCashProvidedByUsedInOperatingActivities",
    "PaymentsForRepurchaseOfCommonStock",
    "PaymentsOfDividends",
    "PaymentsToAcquireBusinessesNetOfCashAcquired",
    "PaymentsToAcquireInvestments",
    "PaymentsToAcquirePropertyPlantAndEquipment",
    "PaymentsToRepayLongTermDebt",
    "PaymentsToRepayShortTermDebt",
    "ProceedsFromIssuanceOfCommonStock",
    "ProceedsFromIssuanceOfLongTermDebt",
    "ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities",
    "ProceedsFromSaleOfInvestments",
    "ProceedsFromSaleOfPropertyPlantAndEquipment",
    "ProceedsFromShortTermDebt",
    "ShareBasedCompensation",

    # EPS and shares
    "CommonStocksSharesAuthorized",
    "CommonStocksSharesIssued",
    "CommonStocksSharesOutstanding",
    "EarningsPerShareBasic",
    "EarningsPerShareDiluted",
    "WeightedAverageNumberOfDilutedSharesOutstanding",
    "WeightedAverageNumberOfSharesOutstandingBasic",

    # Other comprehensive income
    "ComprehensiveIncomeNetOfTax",
    "OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax",
    "OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax",
    "OtherComprehensiveIncomeLossNetOfTax",
    "OtherComprehensiveIncomeUnrealizedHoldingGainLossOnSecuritiesArisingDuringPeriodNetOfTax",
}

DEFAULT_TAXONOMIES = {"us-gaap"}
DEFAULT_FORMS = {"10-K", "10-Q"}
SUPPORTED_REPORT_FORMS = {"10-K", "10-Q"}
